// This file provides a minimal but correct implementation of protoreflect.Message
// for v1alpha1 types, enabling them to be used with the gRPC binary codec.
//
// Background: v1alpha1 types are defined as Go structs with protobuf struct tags
// and have Marshal()/Unmarshal()/Size() methods generated by protoc-gen-gogo.
// They satisfy proto.Message at compile time via the ProtoReflect() stubs in
// proto_reflect_compat.go. However, the gRPC binary codec (google.golang.org/grpc)
// calls proto.Marshal/proto.Unmarshal on these types, which requires ProtoReflect()
// to return a non-nil, functional protoreflect.Message.
//
// This implementation wraps each type with legacyMessage, which satisfies the
// protoreflect.Message interface and delegates Marshal/Unmarshal/Size to the
// existing gogo-generated methods. All field-reflection methods (Range, Get, Set,
// etc.) are intentionally not supported — they would require a compiled proto
// descriptor, which is only available after running protoc. These methods are not
// used in the current gRPC binary or grpc-gateway v2 HTTP paths.

package v1alpha1

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

// v1alpha1Serializable is the interface satisfied by all v1alpha1 message types
// via their gogo-generated Marshal(), Unmarshal(), and Size() methods.
type v1alpha1Serializable interface {
	Marshal() ([]byte, error)
	Unmarshal([]byte) error
	Size() int
}

// legacyMessage is a minimal implementation of protoreflect.Message that provides
// correct proto binary serialization for v1alpha1 types by delegating to their
// existing Marshal/Unmarshal/Size methods.
//
// Only ProtoMethods(), Interface(), and IsValid() are fully implemented.
// All field-reflection methods panic with a descriptive error if called, because
// they require a compiled proto file descriptor that is not embedded in v1alpha1.
type legacyMessage struct {
	self protoreflect.ProtoMessage // the original v1alpha1 type (implements proto.Message)
	ser  v1alpha1Serializable      // same underlying pointer, for fast-path serialization
}

var _ protoreflect.Message = (*legacyMessage)(nil)

func (lm *legacyMessage) Descriptor() protoreflect.MessageDescriptor {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Type() protoreflect.MessageType {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) New() protoreflect.Message {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Interface() protoreflect.ProtoMessage {
	return lm.self
}

func (lm *legacyMessage) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Has(fd protoreflect.FieldDescriptor) bool {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Clear(fd protoreflect.FieldDescriptor) {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Get(fd protoreflect.FieldDescriptor) protoreflect.Value {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Set(fd protoreflect.FieldDescriptor, v protoreflect.Value) {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	panic("proto field reflection not supported for v1alpha1 legacy types: no compiled descriptor available")
}

func (lm *legacyMessage) WhichOneof(od protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	return nil
}

func (lm *legacyMessage) GetUnknown() protoreflect.RawFields {
	return nil
}

func (lm *legacyMessage) SetUnknown(b protoreflect.RawFields) {}

func (lm *legacyMessage) IsValid() bool {
	return lm.self != nil
}

// ProtoMethods returns the fast-path marshal/unmarshal/size methods backed by
// the gogo-generated Marshal(), Unmarshal(), and Size() methods on the wrapped type.
// The gRPC binary codec uses these methods exclusively and never calls the
// reflection methods above.
func (lm *legacyMessage) ProtoMethods() *protoiface.Methods {
	ser := lm.ser
	return &protoiface.Methods{
		Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
			return protoiface.SizeOutput{Size: ser.Size()}
		},
		Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
			b, err := ser.Marshal()
			if err != nil {
				return protoiface.MarshalOutput{}, err
			}
			return protoiface.MarshalOutput{Buf: append(in.Buf, b...)}, nil
		},
		Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
			return protoiface.UnmarshalOutput{}, ser.Unmarshal(in.Buf)
		},
		// CheckInitialized prevents proto.Marshal from falling back to the slow
		// reflection-based checkInitializedSlow path (which calls Descriptor()).
		// v1alpha1 messages use proto3 semantics and have no required fields.
		CheckInitialized: func(in protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
			return protoiface.CheckInitializedOutput{}, nil
		},
	}
}

