issues:
  exclude:
    - SA5011
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - gofmt
    - testifylint
linters-settings:
  testifylint:
    enable-all: true
    disable:
      - compares
      - empty
      - error-nil
      - expected-actual
      - go-require
      - len
      - require-error
run:
  timeout: 50m
