issues:
  exclude:
    - SA5011
  exclude-rules:
    - path: "(applicationset|cmpserver|reposerver|server)/"
      linters:
        - errorlint
    - path: "(applicationset|cmd|cmpserver|controller|pkg|reposerver|server|test)/"
      text: "require-error:"
      linters:
        - testifylint
    - path: "util/(argo|cache)/"
      text: "require-error:"
      linters:
        - testifylint
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - errcheck
    - errorlint
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - unused
    - whitespace 
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj/argo-cd/v2
  testifylint:
    enable-all: true
    disable:
      - error-is-as
      - float-compare
      - go-require
run:
  timeout: 50m
